# PROFILE (local | prod)
# spring.profiles.active=${DIARIO_DE_CLASSE_ACTIVE_PROFILE}
# spring.profiles.active=local
# server.servlet.context-path=/api
# server.error.include-message=always
# server.error.include-binding-errors=always
# logging.level.root=DEBUG

# Define qual profile esta ativo
spring.profiles.active=local

# Configuracoes globais (independentes de profile)
server.servlet.context-path=/api
server.error.include-message=always
server.error.include-binding-errors=always

# Nivel de log global
logging.level.root=DEBUG

# Mensagens do sistema
geral.erro.nao.encontrado.msg=Nenhum registro encontrado.
geral.erro.criar.msg=Erro ao tentar criar.
geral.erro.atualizar.msg=Erro ao tentar atualizar.
usuario.erro.nao.encontrado.msg=Nenhum usuario encontrado.